saas_intelligence:
  target: local
  outputs:
    local:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '../data/warehouse.duckdb') }}"
      schema: analytics
      threads: 4
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SAAS_TRANSFORMER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'SAAS_ETL_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'SAAS_ANALYTICS') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'ANALYTICS') }}"
      threads: 4
      client_session_keep_alive: false
