-- Run as a provisioning admin. Replace the S3 URL and integration name before executing.
-- Warehouse auto-suspend avoids idle compute. Grant these roles to dedicated service users.
CREATE WAREHOUSE IF NOT EXISTS SAAS_ETL_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE DATABASE IF NOT EXISTS SAAS_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.ANALYTICS;
CREATE ROLE IF NOT EXISTS SAAS_TRANSFORMER;
CREATE ROLE IF NOT EXISTS SAAS_BI_READER;
GRANT USAGE ON WAREHOUSE SAAS_ETL_WH TO ROLE SAAS_TRANSFORMER;
GRANT USAGE ON WAREHOUSE SAAS_ETL_WH TO ROLE SAAS_BI_READER;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SAAS_TRANSFORMER;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SAAS_BI_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SAAS_ANALYTICS TO ROLE SAAS_TRANSFORMER;
GRANT USAGE ON SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_BI_READER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA SAAS_ANALYTICS.RAW TO ROLE SAAS_TRANSFORMER;
USE SCHEMA SAAS_ANALYTICS.RAW;
CREATE TABLE IF NOT EXISTS ACCOUNTS (ACCOUNT_ID VARCHAR, SIGNUP_DATE DATE, SEGMENT VARCHAR, REGION VARCHAR, CHANNEL VARCHAR);
CREATE TABLE IF NOT EXISTS USERS (USER_ID VARCHAR, ACCOUNT_ID VARCHAR, CREATED_DATE DATE);
CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (ACCOUNT_ID VARCHAR, MONTH DATE, AMOUNT_CENTS NUMBER(18,0), BILLING_PERIOD VARCHAR, PLAN VARCHAR);
CREATE TABLE IF NOT EXISTS EVENTS (EVENT_ID VARCHAR, USER_ID VARCHAR, ACCOUNT_ID VARCHAR, OCCURRED_AT TIMESTAMP_NTZ, EVENT_NAME VARCHAR, INGESTED_AT TIMESTAMP_NTZ);
CREATE TABLE IF NOT EXISTS OPPORTUNITIES (ACCOUNT_ID VARCHAR, TRIAL_DATE DATE, QUALIFIED_DATE DATE, PAID_DATE DATE);
CREATE TABLE IF NOT EXISTS MARKETING (SPEND_DATE DATE, CHANNEL VARCHAR, SPEND_CENTS NUMBER(18,0));
CREATE TABLE IF NOT EXISTS LOAD_AUDIT (BATCH_ID VARCHAR, LOADED_AT TIMESTAMP_NTZ);
-- Create an AWS storage integration using docs/deployment.md, then replace both placeholders:
CREATE STAGE IF NOT EXISTS SAAS_LANDING URL='s3://YOUR_BUCKET/'
  STORAGE_INTEGRATION=YOUR_STORAGE_INTEGRATION FILE_FORMAT=(TYPE=PARQUET USE_LOGICAL_TYPE=TRUE);
GRANT USAGE ON STAGE SAAS_LANDING TO ROLE SAAS_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.RAW TO ROLE SAAS_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_BI_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_BI_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAAS_ANALYTICS.ANALYTICS TO ROLE SAAS_BI_READER;
